
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 141
#define YY_END_OF_BUFFER 142
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[386] =
    {   0,
        0,    0,    0,    0,  142,  140,  138,  139,   28,   10,
      140,   28,   28,   28,   94,   28,   28,   28,   28,   28,
       28,    3,    3,   28,   28,   28,   28,   28,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   28,
      140,    2,    2,  140,   21,   20,   19,   21,   44,    0,
       23,    0,   67,    0,   46,   70,    0,   64,   62,    0,
       63,    0,    0,    0,    0,   72,   22,    0,   65,    0,
        3,    0,    0,   74,   73,    0,   30,   75,   31,   48,
       40,   42,   37,   49,    8,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   97,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   98,
        0,    0,  132,    0,    0,    0,   55,   83,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  121,    0,    0,    0,    0,   66,
        0,    0,    0,   71,   47,   18,   14,   16,   11,   17,
       15,   13,   12,    6,    0,   93,    0,   27,   43,   38,
       36,   41,   35,   45,    0,   24,    3,    5,    7,    0,
       26,   39,   68,   69,  106,    0,  117,   82,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  128,    0,

        0,    0,    0,    0,   34,    0,    0,  130,    0,    0,
       79,    0,    0,    0,   89,   32,   50,    0,    0,  122,
       55,  104,  102,   54,    0,    0,    0,    0,    0,    0,
        0,  103,  133,    0,    0,    0,  118,    0,    0,  135,
        0,    0,    0,    0,   61,   95,    0,    0,    0,  124,
        0,  125,    0,  126,   91,    0,   80,  127,    0,    0,
      129,    0,    0,   86,    0,   99,    0,    0,   78,    0,
        0,    0,    0,    0,   85,    0,    0,  119,    0,    0,
        0,   77,  101,  115,  113,  100,  134,    0,  123,    0,
        0,    0,  136,   33,    0,   92,    0,    0,    0,   25,

        0,   29,    0,  114,    0,    0,    0,    0,    0,   52,
        0,  131,    0,    0,    0,    9,   58,   57,   51,    0,
        0,  103,    0,   53,    0,    0,    0,    0,   96,    0,
        0,  120,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  105,    0,  116,    0,  137,
       81,    0,    1,    0,    4,   90,   87,   56,    0,   84,
        0,    0,    0,  110,  107,    0,    0,    0,    0,    0,
       88,   60,   59,  109,    0,    0,    0,  111,  112,    0,
      108,    0,    0,   76,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   16,   23,
       24,   25,   16,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,   53,   54,   55,   56,    1,   57,   58,   29,   30,

       59,   60,   61,   34,   62,   36,   37,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   47,   48,   49,   50,
       51,   36,   16,   72,   16,   16,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    2,    3,    4,    1,    4,    4,    1,    1,    1,
        4,    4,    4,    1,    4,    1,    4,    4,    4,    5,
        5,    2,    1,    4,    1,    4,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    4,    1,    4,    2,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    4
    } ;

static yyconst flex_int16_t yy_base[397] =
    {   0,
        0,    0,   70,   71,  691,  692,  692,  692,  666,  692,
      686,    0,   51,   68,  678,  692,  663,  662,   66,  661,
       65,   76,   67,   69,   78,  660,   74,    0,  114,   64,
      107,   69,  111,  130,  665,  692,   72,  138,  159,   45,
       70,  154,  175,  208,  180,   75,   80,  648,   81,  657,
      654,  197,  188,   83,  692,  692,  692,  232,  692,  676,
      692,  670,  692,  610,  692,  692,  665,  692,  692,  672,
      692,  606,   47,   94,  614,  692,  692,  669,  692,   99,
      171,    0,  158,  186,  200,  668,  692,  204,  645,  645,
      692,  692,  692,  644,    0,  118,  163,  637,  636,  161,

      213,  185,  195,  168,  206,   74,  209,  217,  636,  220,
      219,  229,  242,  242,  635,  232,  236,  241,  273,  692,
      262,  240,  692,  265,  255,  615,  253,  692,  263,  270,
      288,  272,  279,  294,  611,  276,  287,  297,  284,  287,
      302,  289,  296,  309,  692,  300,  132,  311,  305,  692,
      605,  599,  321,  692,  692,  692,  692,  692,  692,  692,
      692,  692,  692,  651,  587,  692,  654,  692,  692,  692,
      692,  692,  692,  692,  653,  692,  337,    0,  692,  652,
      692,  692,  692,  692,  692,  317,  692,  692,  337,  325,
      334,  327,  332,  344,  334,  337,  349,  332,  620,  345,

      350,  605,  351,  333,  692,  342,  342,  692,  345,  352,
      353,  623,  399,  354,  692,  692,  692,  358,  362,  374,
      692,  692,  603,  692,  370,  381,  621,  615,  377,  618,
      617,  692,  612,  381,  380,  389,  692,  402,  384,  611,
      391,  401,  579,  398,  692,  692,  546,  599,  534,  692,
      527,  692,  401,  692,  692,  540,  692,  692,  394,  393,
      692,  402,  408,  692,  410,  692,  521,  411,  692,  402,
      400,  418,  402,  451,  692,  405,  409,  692,  430,  538,
      412,  692,  518,  692,  692,  692,  692,  445,  692,  446,
      435,  449,  692,  692,  437,  692,  454,  495,  556,  692,

      492,  692,  446,  692,  444,  535,  461,  446,  522,  692,
      447,  692,  521,  457,  475,  692,  454,  455,  692,  455,
      459,  460,  474,  692,  462,  462,  470,  465,  692,  284,
      168,  692,  471,    0,  482,  495,  489,  494,  197,  491,
      500,  170,  166,  492,  501,  692,  495,  692,  496,  692,
      692,  140,  692,  511,    0,  692,  692,  692,  514,  692,
      504,  515,  516,  692,  692,  503,  508,   96,  127,  513,
      692,  692,  692,  692,  522,   91,   79,  692,  692,   44,
      692,   46,   16,  692,  692,  579,  586,  593,  599,  605,
      612,  619,  622,  628,  635,  637

    } ;

static yyconst flex_int16_t yy_def[397] =
    {   0,
      385,    1,  386,  386,  385,  385,  385,  385,  385,  385,
      387,  388,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  389,  385,  385,  385,  390,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  387,
      385,  388,  385,  385,  385,  385,  385,  385,  385,  391,
      385,  385,  385,  385,  385,  385,  385,  392,  385,  385,
      385,  393,  389,  389,  389,  394,  385,  389,  385,  385,
      385,  385,  385,  385,  390,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  388,  385,  385,  391,  385,  385,  385,
      385,  385,  385,  385,  392,  385,  385,  393,  385,  394,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  395,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  395,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  396,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  396,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,    0,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385

    } ;

static yyconst flex_int16_t yy_nxt[765] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   16,   17,   18,   16,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   36,   36,   38,   39,   40,
       41,   42,   36,   43,   44,   45,   46,   47,   48,   49,
       36,   16,    6,   16,   50,   51,   29,   52,   33,   34,
       35,   37,   38,   39,   40,   41,   42,   36,   53,   44,
       45,   54,   56,   56,   63,   57,   57,   65,   77,  384,
       84,   85,   70,   78,   80,  127,   81,   81,   79,   71,
       86,   66,   87,   80,   89,   81,   81,   93,   94,  109,

       90,   91,  383,  120,  103,  170,  154,  104,  196,  110,
      127,  121,  382,  128,  146,  381,   64,  171,  177,  177,
      147,  149,   58,   58,   72,   82,   73,  109,   74,  103,
       75,  120,  104,  105,  110,  196,  121,  106,  128,  146,
       88,   96,   97,   98,  107,  147,  149,  108,  111,  112,
      113,  380,  172,   99,  155,  377,  115,  100,  101,  102,
      114,  376,  185,  105,  173,  106,  243,  116,  122,  107,
      117,   96,  108,  111,  112,  113,  118,  123,   99,  179,
      129,  385,  100,  101,  102,  124,  115,  185,   80,  125,
       81,   81,  116,  243,  130,  117,  122,  131,  194,  126,

      132,  133,  123,  186,  189,  134,  143,  179,  368,  385,
      129,  192,  363,  144,  133,  124,  362,  125,  134,  130,
      145,  179,  131,  385,  126,  179,  194,  385,  186,  189,
      360,  133,  353,  134,  135,  193,  143,  103,  136,  197,
      104,  192,  137,  195,  133,  145,  153,  190,  138,  202,
      139,  156,  156,  140,  141,  152,  198,  191,  142,  201,
      193,  199,  103,  203,  135,  104,  136,  197,  195,  137,
      204,  205,  210,  138,  190,  139,  207,  202,  140,  211,
      212,  198,  191,  208,  201,  216,  199,  206,  203,  157,
      214,  158,  213,  213,  219,  204,  159,  210,  221,  160,

      161,  162,  163,  207,  211,  212,  222,  215,  208,  217,
      216,  223,  206,  224,  225,  218,  228,  229,  230,  219,
      231,  216,  226,  221,  234,  352,  233,  235,  227,  237,
      236,  222,  215,  239,  217,  240,  223,  242,  224,  241,
      238,  228,  229,  230,  225,  244,  216,  231,  245,  226,
      231,  233,  235,  227,  234,  236,  177,  177,  239,  237,
      240,  250,  242,  251,  252,  238,  254,  241,  253,  255,
      256,  257,  244,  245,  258,  259,  260,  231,  267,  262,
      205,  266,  263,  272,  248,  268,  250,  269,  264,  252,
      270,  254,  271,  251,  255,  253,  257,  275,  276,  258,

      256,  260,  277,  267,  278,  259,  262,  263,  205,  266,
      268,  272,  269,  264,  280,  270,  274,  271,  213,  213,
      281,  284,  275,  276,  288,  289,  290,  277,  291,  292,
      294,  295,  278,  303,  308,  297,  309,  305,  306,  280,
      307,  310,  311,  312,  313,  281,  284,  314,  317,  288,
      289,  290,  318,  319,  292,  294,  320,  322,  291,  295,
      297,  303,  305,  306,  308,  307,  309,  311,  312,  310,
      315,  315,  314,  317,  313,  324,  325,  318,  319,  327,
      326,  328,  322,  316,  329,  332,  320,  335,  333,  336,
      338,  340,  341,  345,  315,  315,  342,  343,  344,  346,

      347,  348,  349,  324,  325,  326,  328,  327,  350,  351,
      332,  316,  329,  333,  336,  338,  354,  335,  340,  356,
      345,  342,  343,  344,  346,  357,  348,  349,  359,  358,
      347,  361,  316,  350,  351,  365,  364,  369,  366,  367,
      370,  354,  375,  371,  356,  372,  373,  374,  379,  339,
      378,  337,  334,  357,  358,  359,  361,  331,  300,  330,
      316,  364,  365,  366,  367,  323,  321,  369,  371,  375,
      370,  296,  374,  372,  373,  378,  304,  302,  379,   55,
       55,   55,   55,   55,   55,   55,   60,   60,   60,   60,
       60,   60,   60,   62,   62,  301,   62,   62,   62,   62,

       83,  300,   83,   83,   83,   83,   95,  298,  296,   95,
       95,   95,  167,  167,  167,  167,  167,  167,  167,  175,
      175,  175,  175,  175,  175,  175,  178,  178,  180,  180,
      180,  180,  180,  180,  180,  299,  299,  299,  299,  299,
      299,  299,  355,  355,  293,  287,  286,  285,  283,  282,
      279,  273,  265,  261,  181,  176,  168,  249,  164,  247,
      246,  232,  220,  209,  200,  188,  187,  184,  183,  182,
      181,  176,  174,  169,  168,  166,  165,  164,   61,  151,
      150,  148,  119,   92,   76,   69,   68,   67,   61,   59,
      385,    5,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385
    } ;

static yyconst flex_int16_t yy_chk[765] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,   13,    3,    4,   14,   21,  383,
       24,   24,   19,   21,   23,   40,   23,   23,   21,   19,
       24,   14,   24,   22,   25,   22,   22,   27,   27,   32,

       25,   25,  382,   37,   30,   73,   54,   30,  106,   32,
       40,   37,  380,   41,   46,  377,   13,   73,   80,   80,
       47,   49,    3,    4,   19,   22,   19,   32,   19,   30,
       19,   37,   30,   31,   32,  106,   37,   31,   41,   46,
       24,   29,   29,   29,   31,   47,   49,   31,   33,   33,
       33,  376,   74,   29,   54,  369,   34,   29,   29,   29,
       33,  368,   96,   31,   74,   31,  147,   34,   38,   31,
       34,   29,   31,   33,   33,   33,   34,   38,   29,   83,
       42,   83,   29,   29,   29,   39,   34,   96,   81,   39,
       81,   81,   34,  147,   42,   34,   38,   42,  104,   39,

       42,   43,   38,   97,  100,   43,   45,   84,  352,   84,
       42,  102,  343,   45,   53,   39,  342,   39,   53,   42,
       45,   85,   42,   85,   39,   88,  104,   88,   97,  100,
      339,   43,  331,   43,   44,  103,   45,   52,   44,  107,
       52,  102,   44,  105,   53,   45,   53,  101,   44,  111,
       44,   58,   58,   44,   44,   52,  108,  101,   44,  110,
      103,  108,   52,  111,   44,   52,   44,  107,  105,   44,
      112,  113,  116,   44,  101,   44,  114,  111,   44,  117,
      118,  108,  101,  114,  110,  122,  108,  113,  111,   58,
      121,   58,  119,  119,  125,  112,   58,  116,  127,   58,

       58,   58,   58,  114,  117,  118,  129,  121,  114,  124,
      122,  130,  113,  130,  131,  124,  132,  132,  133,  125,
      134,  136,  131,  127,  138,  330,  137,  139,  131,  141,
      140,  129,  121,  142,  124,  143,  130,  146,  130,  144,
      141,  132,  132,  133,  131,  148,  136,  153,  149,  131,
      134,  137,  139,  131,  138,  140,  177,  177,  142,  141,
      143,  186,  146,  189,  190,  141,  192,  144,  191,  193,
      194,  195,  148,  149,  196,  197,  198,  153,  204,  200,
      201,  203,  200,  211,  153,  206,  186,  207,  200,  190,
      209,  192,  210,  189,  193,  191,  195,  214,  218,  196,

      194,  198,  219,  204,  220,  197,  200,  200,  201,  203,
      206,  211,  207,  200,  225,  209,  213,  210,  213,  213,
      226,  229,  214,  218,  234,  235,  236,  219,  238,  239,
      241,  242,  220,  253,  263,  244,  265,  259,  260,  225,
      262,  268,  270,  271,  272,  226,  229,  273,  276,  234,
      235,  236,  277,  277,  239,  241,  279,  281,  238,  242,
      244,  253,  259,  260,  263,  262,  265,  270,  271,  268,
      274,  274,  273,  276,  272,  288,  290,  277,  277,  292,
      291,  295,  281,  274,  297,  303,  279,  307,  305,  308,
      311,  314,  315,  321,  315,  315,  317,  318,  320,  322,

      323,  325,  326,  288,  290,  291,  295,  292,  327,  328,
      303,  274,  297,  305,  308,  311,  333,  307,  314,  335,
      321,  317,  318,  320,  322,  336,  325,  326,  338,  337,
      323,  340,  341,  327,  328,  345,  344,  354,  347,  349,
      359,  333,  367,  361,  335,  362,  363,  366,  375,  313,
      370,  309,  306,  336,  337,  338,  340,  301,  299,  298,
      341,  344,  345,  347,  349,  283,  280,  354,  361,  367,
      359,  267,  366,  362,  363,  370,  256,  251,  375,  386,
      386,  386,  386,  386,  386,  386,  387,  387,  387,  387,
      387,  387,  387,  388,  388,  249,  388,  388,  388,  388,

      389,  248,  389,  389,  389,  389,  390,  247,  243,  390,
      390,  390,  391,  391,  391,  391,  391,  391,  391,  392,
      392,  392,  392,  392,  392,  392,  393,  393,  394,  394,
      394,  394,  394,  394,  394,  395,  395,  395,  395,  395,
      395,  395,  396,  396,  240,  233,  231,  230,  228,  227,
      223,  212,  202,  199,  180,  175,  167,  165,  164,  152,
      151,  135,  126,  115,  109,   99,   98,   94,   90,   89,
       86,   78,   75,   72,   70,   67,   64,   62,   60,   51,
       50,   48,   35,   26,   20,   18,   17,   15,   11,    9,
        5,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./lexico.l"
/* Leo Gutiérrez Ramírez, leorocko13@hotmail.com */
#line 3 "./lexico.l"
	#include <stdlib.h>
	#include "estructuras.h"
	#include "constantes.h"
	#include "y.tab.h"
	extern char opVar[4];
	extern unsigned int lineno;
	char buf[100];
	char *s;			/* Puntero para ir acumulando caracteres de escape */

#line 769 "lex.yy.c"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 14 "./lexico.l"


#line 960 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 386 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 692 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "./lexico.l"
yylineno;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "./lexico.l"
{
						/* TODO Revisar esto con calma */
						if(isupper(*yytext))
							yylval.sIndex = tolower(*yytext) - 'a';
						else
							yylval.sIndex = *yytext - 'a';
						return VARIABLE;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "./lexico.l"
{
						yylval.iValue = atof(yytext);
						return INTEGER;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "./lexico.l"
{	
									char *__elemento = strtok(yytext, ".");
									__elemento = strtok(NULL, ".");
									/*printf("Detectado: '%s'\n", __elemento);*/

									unsigned i;
									for(i = 0; i < N_CONST; i++) {
										if(strcmp(__elemento, consts[i].const_str) == 0) {
											yylval.iValue = consts[i].value;
											return INTEGER;
										}
									}
									fprintf(stderr, "Error, constante no identificada 'const.%s'\n", __elemento);
									exit(EXIT_FAILURE);
									
								}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "./lexico.l"
{
						/*char *__p;	*/
						/* SHIT */
						/*long long n = strtoll(yytext, &__p, 16);
						if(*__p == 0)*/
							yylval.iValue = atof(yytext);
						/*else
							yylval.iValue = 0;*/
						return INTEGER;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "./lexico.l"
{
						strcpy(yylval.nameFunction, yytext);
						yylval.nameFunction[strlen(yylval.nameFunction)] = '\0';
						return FUNCNAME;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "./lexico.l"
{
							unsigned _i_;
							strcpy(yylval.identificador, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.identificador); _i_++)
								if(isalpha(yylval.identificador[_i_]) && isupper(yylval.identificador[_i_]))
									yylval.identificador[_i_] = tolower(yylval.identificador[_i_]);
							return ID;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "./lexico.l"
{
							
							unsigned _i_;
							strcpy(yylval.idArray, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.idArray); _i_++)
								if(isalpha(yylval.idArray[_i_]) && isupper(yylval.idArray[_i_]))
									yylval.idArray[_i_] = tolower(yylval.idArray[_i_]);
							return ID_ARRAY;

}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "./lexico.l"
{
	/* Detección de gigantes: */
	/* Cortando los caracteres sobrantes: */
	*yytext++;
	*yytext++;
	yytext[strlen(yytext) - 1] = '\0';
	yytext[strlen(yytext) - 1] = '\0';
	unsigned _i_;
	strcpy(yylval.idgigante, yytext);
	for(_i_ = 0; _i_ < strlen(yylval.idgigante); _i_++)
		if(isalpha(yylval.idgigante[_i_]) && isupper(yylval.idgigante[_i_]))
			yylval.idgigante[_i_] = tolower(yylval.idgigante[_i_]);
	printf("Gigante detectado '%s'-'%d'\n", yylval.idgigante, strlen(yylval.idgigante));
	return ID_GIGANTE;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "./lexico.l"
{ BEGIN	STRING; s = buf; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "./lexico.l"
{ *s++ = '\n'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "./lexico.l"
{ *s++ = '\t'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "./lexico.l"
{ *s++ = ' ';  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "./lexico.l"
{ *s++ = '\b'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "./lexico.l"
{ *s++ = '\r'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "./lexico.l"
{ *s++ = '\f'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "./lexico.l"
{ *s++ = '"'; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "./lexico.l"
{ 
				/* FIXME No funcionando! */
					int _ii;
					/* Caracteres de escape numéricos para saltos de línea */
					for(_ii = 0; _ii < (*(yytext + 1) - '0'); _ii++) 
						*s++ = '\n';	
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "./lexico.l"
{
						*s = 0;
						BEGIN 0; 
						/* REGRESAR EL STRING Y ASIGNARLO AQUÍ */
						strcpy(yylval.cadena, buf);
						return CADENA;
					}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 123 "./lexico.l"
{ printf("Error, Invalid string at line: %d\n", lineno + 1); exit(EXIT_FAILURE);	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "./lexico.l"
{ *s++ = *yytext; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 126 "./lexico.l"
{comment();}	/* Comentarios */
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 127 "./lexico.l"
{;}		/* Comentarios tipo shell, perl, python, etc */
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 128 "./lexico.l"
{;}		/* Comentarios estilo C++ */
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 129 "./lexico.l"
{;}		/* Comentarios estilo basic */
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 130 "./lexico.l"
{;}		/* Comentarios estilo batch */
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 131 "./lexico.l"
{;}		/* Comentarios estilo SQL */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 133 "./lexico.l"
{
									return *yytext;
					}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 137 "./lexico.l"
return ARRAY;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 138 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 139 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 140 "./lexico.l"
return LETSET;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 141 "./lexico.l"
return IFTHEN;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 142 "./lexico.l"
return IFEND;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 143 "./lexico.l"
return _LT_;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 144 "./lexico.l"
return _GT_;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 145 "./lexico.l"
return GE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 146 "./lexico.l"
return GE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 147 "./lexico.l"
return SWAP;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 148 "./lexico.l"
return LE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 149 "./lexico.l"
return LE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 150 "./lexico.l"
return EQ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 151 "./lexico.l"
return EQ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 152 "./lexico.l"
return NE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 153 "./lexico.l"
return NE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 154 "./lexico.l"
return AND;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 155 "./lexico.l"
return OR;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 156 "./lexico.l"
return SHIFTLEFT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 157 "./lexico.l"
return SHIFTRIGHT; 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 158 "./lexico.l"
return EXPR_MAS;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 159 "./lexico.l"
return EXPR_MENOS;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 160 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 161 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 162 "./lexico.l"
return EXPR_MUL;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 163 "./lexico.l"
return EXPR_NOT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 164 "./lexico.l"
return EXPR_ELEVADO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 165 "./lexico.l"
return EXPR_MENOR;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 166 "./lexico.l"
return EXPR_MAYOR;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 167 "./lexico.l"
return EXPR_MENORQUE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 168 "./lexico.l"
return EXPR_MAYORQUE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 169 "./lexico.l"
return XOROP;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 170 "./lexico.l"
return ASIGN_ADD;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 171 "./lexico.l"
return ASIGN_SUB;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 172 "./lexico.l"
return ASIGN_MUL;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 173 "./lexico.l"
return ASIGN_DIV;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 174 "./lexico.l"
return ASIGN_POW;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 175 "./lexico.l"
return ASIGN_MOD;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 176 "./lexico.l"
return ASIGN_SHIFTLEFT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 177 "./lexico.l"
return ASIGN_SHIFTRIGHT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 178 "./lexico.l"
return ASIGN_AND;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 179 "./lexico.l"
return ASIGN_OR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 180 "./lexico.l"
return CONCATENATE_DIGITS;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 181 "./lexico.l"
return FACE_HAPPY;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 182 "./lexico.l"
return FACE_SAD;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 183 "./lexico.l"
return FACE_NO;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 184 "./lexico.l"
return PRINCIPIO;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 185 "./lexico.l"
return PROC;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 186 "./lexico.l"
return EXIT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 187 "./lexico.l"
return FOR;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 188 "./lexico.l"
return CALL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 189 "./lexico.l"
return UNLESS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 190 "./lexico.l"
return AND;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 191 "./lexico.l"
return OR;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 192 "./lexico.l"
return FOREACH;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "./lexico.l"
return INCREMENTAR;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 194 "./lexico.l"
return DECREMENTAR;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 195 "./lexico.l"
return DECLARE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 196 "./lexico.l"
return FUNCTION;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 197 "./lexico.l"
return INT_TYPE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 198 "./lexico.l"
return DECIMAL_TYPE;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 199 "./lexico.l"
return BOOL_TYPE;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 200 "./lexico.l"
return VOID;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 201 "./lexico.l"
return ANDBITS;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 202 "./lexico.l"
return ORBITS;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 203 "./lexico.l"
return OPVAR;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 204 "./lexico.l"
return WHILE;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 205 "./lexico.l"
return DO;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 206 "./lexico.l"
return IF;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 207 "./lexico.l"
return ELSE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 208 "./lexico.l"
return READ;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 209 "./lexico.l"
return PUSH;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 210 "./lexico.l"
return POP;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 211 "./lexico.l"
return PRINT;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 212 "./lexico.l"
return PAR;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 213 "./lexico.l"
return PRINTN;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 214 "./lexico.l"
return ABS;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 215 "./lexico.l"
return PRASCII;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 216 "./lexico.l"
return CLEAR_STACK;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 217 "./lexico.l"
return PUSH_VARS;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 218 "./lexico.l"
return POP_VARS;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 219 "./lexico.l"
return FACTORIAL;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 220 "./lexico.l"
return SUMATORIA;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 221 "./lexico.l"
return RAND;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 222 "./lexico.l"
return BREAK;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 223 "./lexico.l"
return PUTS;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 224 "./lexico.l"
return STRLEN;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 225 "./lexico.l"
return ADDASM;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 226 "./lexico.l"
return SUBASM;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 227 "./lexico.l"
return MOVE;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 228 "./lexico.l"
return MOVE;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 229 "./lexico.l"
return TO;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 230 "./lexico.l"
return MOVASM;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 231 "./lexico.l"
return SQRT;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 232 "./lexico.l"
return ACOS;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 233 "./lexico.l"
return ASIN;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 234 "./lexico.l"
return ATAN;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 235 "./lexico.l"
return CEIL;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 236 "./lexico.l"
return COS;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 237 "./lexico.l"
return COSH;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 238 "./lexico.l"
return EXP;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 239 "./lexico.l"
return FLOOR;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 240 "./lexico.l"
return LN;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 241 "./lexico.l"
return SIN;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 242 "./lexico.l"
return SINH;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 243 "./lexico.l"
return TAN;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 244 "./lexico.l"
return TANH;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 245 "./lexico.l"
return SYSTEM;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 246 "./lexico.l"
;
	YY_BREAK
case 139:
/* rule 139 can match eol */
YY_RULE_SETUP
#line 247 "./lexico.l"
{ lineno++; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 248 "./lexico.l"
{
				char __linea[40];
				sprintf(__linea, "Carácter desconocido en la línea %d\n", lineno + 1);
				fputs(__linea, stdout);

				/* FIXME Decidir si se va a continuar o al error parar todo */
				
				/*yyerror(__linea);*/
	}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 258 "./lexico.l"
ECHO;
	YY_BREAK
#line 1845 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 386 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 386 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 385);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 258 "./lexico.l"



comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0);
/*		putchar(c);*/

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	/*if (c != 0)
		putchar(c1);*/
}

int yywrap(void) {
	return 1;
}

