
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 142
#define YY_END_OF_BUFFER 143
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[377] =
    {   0,
        0,    0,    0,    0,  143,  141,  139,  140,   29,   11,
      141,   29,   29,   29,   94,   29,   29,   29,   29,   29,
       29,    3,    3,   29,   29,   29,   29,   29,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   29,
      141,    2,  141,   22,   21,   20,   22,   45,    0,   24,
        0,   68,    0,   47,   71,    0,   65,   63,    0,   64,
        0,    0,    0,    0,   73,   23,    0,   66,    0,    3,
        4,    0,    0,   75,   74,    0,   31,   76,   32,   49,
       41,   43,   38,   50,    9,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   97,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   98,
        0,    0,  132,    0,    0,    0,   56,   83,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  121,    0,    0,    0,    0,   67,
        0,    0,   72,   48,   19,   15,   17,   12,   18,   16,
       14,   13,    7,    0,   93,    0,   28,   44,   39,   37,
       42,   36,   46,    0,   25,    3,    6,    8,    0,   27,
       40,   69,   70,  106,    0,  117,   82,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  128,    0,    0,

        0,    0,    0,   35,    0,    0,  130,    0,    0,   79,
        0,    0,    0,   89,   33,   51,    0,    0,  122,   56,
      104,  102,   55,    0,    0,    0,    0,    0,    0,    0,
      103,  133,    0,    0,    0,  118,    0,    0,  135,    0,
        0,    0,    0,   62,   95,    0,    0,  124,    0,  125,
        0,  126,   91,    0,   80,  127,    0,    0,  129,    0,
        0,   86,    0,   99,    0,    0,   78,    0,    0,    0,
        0,    0,   85,    0,    0,  119,    0,    0,    0,   77,
      101,  115,  113,  100,  134,    0,  123,    0,    0,    0,
      136,   34,    0,   92,    0,    0,   26,    0,   30,    0,

      114,    0,    0,    0,    0,    0,   53,    0,  131,    0,
        0,    0,   10,   59,   58,   52,    0,    0,  103,    0,
       54,    0,    0,    0,    0,   96,    0,  120,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  105,    0,  116,    0,  137,   81,    1,    0,    5,
       90,   87,   57,    0,   84,    0,    0,    0,  110,  107,
        0,    0,    0,    0,    0,   88,   61,   60,  109,    0,
        0,  138,  111,  112,  108,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   16,   23,
       24,   25,   16,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,   53,   54,   55,   56,    1,   27,   57,   29,   30,

       58,   59,   60,   34,   61,   36,   37,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   47,   48,   49,   50,
       51,   36,   16,   71,   16,   16,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    2,    3,    4,    1,    4,    4,    1,    1,    1,
        4,    4,    4,    1,    4,    1,    4,    4,    4,    5,
        5,    2,    1,    4,    1,    4,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    4,    1,    4,    2,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        4
    } ;

static yyconst flex_int16_t yy_base[388] =
    {   0,
        0,    0,   69,   70,  661,  662,  662,  662,  636,  662,
      656,    0,   50,   67,  648,  662,  633,  632,   66,  631,
       65,   60,   67,   82,   75,  630,   72,    0,  126,   64,
       76,   78,  111,  138,  635,  662,   81,  104,  150,   60,
       74,  157,  106,  199,  172,   99,  117,  618,  128,  627,
      624,  161,   88,  662,  662,  662,  208,  662,  646,  662,
      640,  662,  581,  662,  662,  635,  662,  662,  642,  662,
      577,   90,  139,  585,  662,  662,  639,  662,  126,  203,
      662,    0,  156,  165,  183,  638,  662,  188,  615,  615,
      662,  662,  662,  614,    0,  166,  173,  607,  606,  173,

      213,  608,  179,  185,  189,   96,  201,  216,  605,  191,
      223,  205,  203,  244,  604,  229,  239,  244,  232,  662,
      258,  242,  662,  244,  250,  584,  245,  662,  249,  254,
      284,  254,  257,  604,  579,  256,  263,   54,  262,  265,
      290,  271,  291,  301,  662,  296,  300,  301,  295,  662,
      573,   89,  662,  662,  662,  662,  662,  662,  662,  662,
      662,  662,  620,  557,  662,  623,  662,  662,  662,  662,
      662,  662,  662,  622,  662,  317,    0,  662,  621,  662,
      662,  662,  662,  662,  296,  662,  662,  596,  302,  308,
      304,  308,  595,  310,  313,  594,  307,  586,  329,  323,

      571,  325,  314,  662,  327,  328,  662,  332,  338,  349,
      589,  367,  338,  662,  662,  662,  345,  348,  361,  662,
      662,  569,  662,  348,  354,  587,  581,  351,  584,  583,
      662,  578,  355,  354,  363,  662,  584,  358,  576,  365,
      377,  579,  371,  662,  662,  605,  511,  662,  520,  662,
      378,  662,  662,  528,  662,  662,  368,  369,  662,  377,
      532,  662,  514,  662,  488,  383,  662,  380,  378,  511,
      380,  410,  662,  383,  403,  662,  509,  505,  386,  662,
      483,  662,  662,  662,  662,  403,  662,  406,  396,  418,
      662,  662,  399,  662,  421,  527,  662,  464,  662,  413,

      662,  409,  510,  499,  413,  492,  662,  414,  662,  488,
      424,  442,  662,  422,  424,  662,  425,  438,  434,  428,
      662,  440,  442,  445,  441,  662,  293,  662,  441,    0,
      450,  444,  449,  457,  267,  454,  461,  215,  192,  451,
      462,  662,  456,  662,  457,  662,  662,  662,  191,    0,
      662,  146,  662,  159,  662,  463,  474,  475,  662,  662,
      468,  474,  138,  482,  478,  662,  662,  662,  662,   75,
       49,  662,  662,  662,  662,  662,  542,  549,  556,  562,
      568,  575,  582,  585,  591,  598,  600
    } ;

static yyconst flex_int16_t yy_def[388] =
    {   0,
      376,    1,  377,  377,  376,  376,  376,  376,  376,  376,
      378,  379,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  380,  376,  376,  376,  381,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  378,  376,
      379,  376,  376,  376,  376,  376,  376,  376,  382,  376,
      376,  376,  376,  376,  376,  376,  383,  376,  376,  376,
      376,  384,  380,  380,  380,  385,  376,  380,  376,  376,
      376,  376,  376,  376,  381,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  379,  376,  376,  382,  376,  376,  376,  376,
      376,  376,  376,  383,  376,  376,  384,  376,  385,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  386,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  386,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  387,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  387,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,    0,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376
    } ;

static yyconst flex_int16_t yy_nxt[734] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   16,   17,   18,   16,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   36,   36,   38,   39,   40,
       41,   42,   36,   43,   44,   45,   46,   47,   48,   49,
       36,   16,    6,   16,   50,   51,   30,   33,   34,   35,
       37,   38,   39,   40,   41,   42,   36,   52,   44,   45,
       53,   55,   55,   62,   56,   56,   64,   79,   76,   80,
       80,  233,   69,   77,   79,  375,   80,   80,   78,   70,
       65,   89,   81,   84,   85,   93,   94,   90,   91,   81,

      127,  374,  105,   86,  103,   87,  106,  104,  109,   82,
      233,  153,  120,  107,   63,  230,  108,  128,  110,   81,
      121,   57,   57,   71,  127,   72,   81,   73,  103,   74,
      195,  104,  133,  106,  122,  109,  134,  107,  146,  120,
      108,  128,  110,  123,  121,  176,  176,  169,  111,  112,
      113,  246,   88,   96,   97,   98,  195,  147,  154,  170,
      114,  122,  146,  134,  115,   99,  371,  123,  149,  100,
      101,  102,  111,  112,  113,  116,  124,  178,  117,  376,
      125,  147,   96,  129,  118,  365,  178,  133,  376,   99,
      126,  134,  149,  100,  101,  102,  171,  130,  143,  116,

      131,  364,  117,  132,  178,  144,  376,  125,  172,  178,
      184,  376,  145,  185,  126,  193,  188,  363,  152,  192,
       79,  130,   80,   80,  131,  135,  194,  155,  155,  136,
      200,  196,  204,  137,  184,   81,  145,  185,  358,  138,
      188,  139,  193,  192,  140,  141,  203,  189,  205,  142,
      194,  212,  212,  201,  200,  197,  136,  190,  196,  137,
      198,  357,   81,  138,  156,  139,  157,  202,  140,  209,
      203,  158,  205,  189,  159,  160,  161,  162,  206,  197,
      201,  190,  210,  211,  198,  207,  213,  215,  216,  218,
      220,  202,  221,  209,  217,  222,  229,  223,  227,  228,

      355,  215,  232,  214,  206,  234,  210,  211,  235,  207,
      224,  215,  216,  218,  220,  238,  221,  236,  225,  222,
      229,  223,  227,  228,  226,  215,  232,  214,  237,  234,
      239,  240,  235,  241,  242,  243,  176,  176,  244,  238,
      248,  250,  251,  252,  225,  253,  236,  255,  226,   81,
      256,  258,  237,  204,  239,  264,  348,  241,  240,  265,
      242,  243,  244,  260,  248,  250,  261,  252,  251,  253,
      266,  255,  262,  267,  256,  258,   81,  268,  269,  270,
      204,  273,  264,  265,  272,  274,  212,  212,  275,  260,
      261,  276,  278,  279,  266,  282,  262,  267,  286,  287,

      288,  268,  269,  290,  292,  273,  270,  293,  295,  274,
      300,  302,  275,  307,  303,  304,  278,  279,  276,  282,
      308,  309,  286,  287,  288,  311,  314,  290,  292,  312,
      312,  319,  295,  321,  293,  302,  322,  300,  303,  304,
      307,  323,  313,  325,  308,  309,  315,  316,  324,  311,
      314,  326,  328,  329,  343,  319,  332,  334,  336,  337,
      321,  312,  312,  322,  338,  323,  339,  325,  340,  313,
      315,  316,  341,  342,  352,  324,  328,  329,  326,  344,
      332,  334,  345,  346,  336,  347,  349,  351,  338,  353,
      339,  354,  340,  313,  356,  359,  360,  342,  341,  361,

      362,  352,  366,  344,  367,  368,  345,  346,  370,  347,
      349,  351,  369,  353,  372,  373,  335,  354,  356,  359,
      313,  333,  360,  361,  362,  331,  366,  330,  327,  297,
      320,  367,  368,  318,  370,  317,  369,  310,  294,  373,
      306,  372,   54,   54,   54,   54,   54,   54,   54,   59,
       59,   59,   59,   59,   59,   59,   61,   61,  305,   61,
       61,   61,   61,   83,  301,   83,   83,   83,   83,   95,
      299,  298,   95,   95,   95,  166,  166,  166,  166,  166,
      166,  166,  174,  174,  174,  174,  174,  174,  174,  177,
      177,  179,  179,  179,  179,  179,  179,  179,  296,  296,

      296,  296,  296,  296,  296,  350,  350,  297,  294,  291,
      289,  285,  284,  283,  281,  280,  277,  271,  263,  259,
      257,  254,  249,  180,  175,  167,  247,  163,  245,  231,
      230,  219,  208,  199,  191,  187,  186,  183,  182,  181,
      180,  175,  173,  168,  167,  165,  164,  163,   60,  151,
      150,  148,  119,   92,   75,   68,   67,   66,   60,   58,
      376,    5,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376
    } ;

static yyconst flex_int16_t yy_chk[734] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,   13,    3,    4,   14,   22,   21,   22,
       22,  138,   19,   21,   23,  371,   23,   23,   21,   19,
       14,   25,   22,   24,   24,   27,   27,   25,   25,   23,

       40,  370,   31,   24,   30,   24,   31,   30,   32,   22,
      138,   53,   37,   31,   13,  152,   31,   41,   32,   22,
       37,    3,    4,   19,   40,   19,   23,   19,   30,   19,
      106,   30,   43,   31,   38,   32,   43,   31,   46,   37,
       31,   41,   32,   38,   37,   79,   79,   72,   33,   33,
       33,  152,   24,   29,   29,   29,  106,   47,   53,   72,
       33,   38,   46,   43,   34,   29,  363,   38,   49,   29,
       29,   29,   33,   33,   33,   34,   39,   83,   34,   83,
       39,   47,   29,   42,   34,  354,   84,   52,   84,   29,
       39,   52,   49,   29,   29,   29,   73,   42,   45,   34,

       42,  352,   34,   42,   85,   45,   85,   39,   73,   88,
       96,   88,   45,   97,   39,  104,  100,  349,   52,  103,
       80,   42,   80,   80,   42,   44,  105,   57,   57,   44,
      110,  107,  113,   44,   96,   80,   45,   97,  339,   44,
      100,   44,  104,  103,   44,   44,  112,  101,  113,   44,
      105,  119,  119,  111,  110,  108,   44,  101,  107,   44,
      108,  338,   80,   44,   57,   44,   57,  111,   44,  116,
      112,   57,  113,  101,   57,   57,   57,   57,  114,  108,
      111,  101,  117,  118,  108,  114,  121,  122,  124,  125,
      127,  111,  129,  116,  124,  130,  133,  130,  132,  132,

      335,  136,  137,  121,  114,  139,  117,  118,  140,  114,
      131,  122,  124,  125,  127,  142,  129,  141,  131,  130,
      133,  130,  132,  132,  131,  136,  137,  121,  141,  139,
      143,  144,  140,  146,  147,  148,  176,  176,  149,  142,
      185,  189,  190,  191,  131,  192,  141,  194,  131,  176,
      195,  197,  141,  200,  143,  202,  327,  146,  144,  203,
      147,  148,  149,  199,  185,  189,  199,  191,  190,  192,
      205,  194,  199,  206,  195,  197,  176,  208,  209,  210,
      200,  213,  202,  203,  212,  217,  212,  212,  218,  199,
      199,  219,  224,  225,  205,  228,  199,  206,  233,  234,

      235,  208,  209,  238,  240,  213,  210,  241,  243,  217,
      251,  257,  218,  266,  258,  260,  224,  225,  219,  228,
      268,  269,  233,  234,  235,  271,  274,  238,  240,  272,
      272,  279,  243,  286,  241,  257,  288,  251,  258,  260,
      266,  289,  272,  293,  268,  269,  275,  275,  290,  271,
      274,  295,  300,  302,  320,  279,  305,  308,  311,  312,
      286,  312,  312,  288,  314,  289,  315,  293,  317,  272,
      275,  275,  318,  319,  332,  290,  300,  302,  295,  322,
      305,  308,  323,  324,  311,  325,  329,  331,  314,  333,
      315,  334,  317,  337,  336,  340,  341,  319,  318,  343,

      345,  332,  356,  322,  357,  358,  323,  324,  362,  325,
      329,  331,  361,  333,  364,  365,  310,  334,  336,  340,
      337,  306,  341,  343,  345,  304,  356,  303,  298,  296,
      281,  357,  358,  278,  362,  277,  361,  270,  265,  365,
      263,  364,  377,  377,  377,  377,  377,  377,  377,  378,
      378,  378,  378,  378,  378,  378,  379,  379,  261,  379,
      379,  379,  379,  380,  254,  380,  380,  380,  380,  381,
      249,  247,  381,  381,  381,  382,  382,  382,  382,  382,
      382,  382,  383,  383,  383,  383,  383,  383,  383,  384,
      384,  385,  385,  385,  385,  385,  385,  385,  386,  386,

      386,  386,  386,  386,  386,  387,  387,  246,  242,  239,
      237,  232,  230,  229,  227,  226,  222,  211,  201,  198,
      196,  193,  188,  179,  174,  166,  164,  163,  151,  135,
      134,  126,  115,  109,  102,   99,   98,   94,   90,   89,
       86,   77,   74,   71,   69,   66,   63,   61,   59,   51,
       50,   48,   35,   26,   20,   18,   17,   15,   11,    9,
        5,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./lexico.l"
/* Leo Gutiérrez Ramírez, leorocko13@hotmail.com */
#line 3 "./lexico.l"
	#include <stdlib.h>
	#include "estructuras.h"
	#include "constantes.h"
	#include "y.tab.h"
	extern char opVar[4];
	extern unsigned int lineno;
	char buf[100];
	char *str_scapes;			/* Puntero para ir acumulando caracteres de escape */

#line 758 "lex.yy.c"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 14 "./lexico.l"


#line 949 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 377 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 662 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "./lexico.l"
yylineno;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "./lexico.l"
{
						/* TODO Revisar esto con calma */
						if(isupper(*yytext))
							yylval.sIndex = tolower(*yytext) - 'a';
						else
							yylval.sIndex = *yytext - 'a';
						return VARIABLE;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "./lexico.l"
{
						yylval.iValue = atof(yytext);
						return INTEGER;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "./lexico.l"
{
		/* Cortar la 'g' */
		yytext[strlen(yytext) - 1] = '\0';		
		strcpy(yylval.cadena_gigante, yytext);
		return GIGANTE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "./lexico.l"
{	
									char *__elemento = strtok(yytext, ".");
									__elemento = strtok(NULL, ".");
									/*printf("Detectado: '%s'\n", __elemento);*/

									unsigned i;
									for(i = 0; i < N_CONST; i++) {
										if(strcmp(__elemento, consts[i].const_str) == 0) {
											yylval.iValue = consts[i].value;
											return INTEGER;
										}
									}
									fprintf(stderr, "Error, constante no identificada 'const.%s'\n", __elemento);
									exit(EXIT_FAILURE);
									
								}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "./lexico.l"
{
						/*char *__p;	*/
						/* SHIT */
						/*long long n = strtoll(yytext, &__p, 16);
						if(*__p == 0)*/
							yylval.iValue = atof(yytext);
						/*else
							yylval.iValue = 0;*/
						return INTEGER;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "./lexico.l"
{
						strcpy(yylval.nameFunction, yytext);
						yylval.nameFunction[strlen(yylval.nameFunction)] = '\0';
						return FUNCNAME;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 "./lexico.l"
{
							unsigned _i_;
							strcpy(yylval.identificador, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.identificador); _i_++)
								if(isalpha(yylval.identificador[_i_]) && isupper(yylval.identificador[_i_]))
									yylval.identificador[_i_] = tolower(yylval.identificador[_i_]);
							return ID;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "./lexico.l"
{
							
							unsigned _i_;
							strcpy(yylval.idArray, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.idArray); _i_++)
								if(isalpha(yylval.idArray[_i_]) && isupper(yylval.idArray[_i_]))
									yylval.idArray[_i_] = tolower(yylval.idArray[_i_]);
							return ID_ARRAY;

}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "./lexico.l"
{
	/* Detección de gigantes: */
	/* Cortando los caracteres sobrantes: */
	*yytext++;
	*yytext++;
	yytext[strlen(yytext) - 1] = '\0';
	yytext[strlen(yytext) - 1] = '\0';
	unsigned _i_;
	strcpy(yylval.idgigante, yytext);
	for(_i_ = 0; _i_ < strlen(yylval.idgigante); _i_++)
		if(isalpha(yylval.idgigante[_i_]) && isupper(yylval.idgigante[_i_]))
			yylval.idgigante[_i_] = tolower(yylval.idgigante[_i_]);
	/*printf("Gigante detectado '%s'-'%d'\n", yylval.idgigante, strlen(yylval.idgigante));*/
	return ID_GIGANTE;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "./lexico.l"
{ BEGIN	STRING; str_scapes = buf; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "./lexico.l"
{ *str_scapes++ = '\n'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "./lexico.l"
{ *str_scapes++ = '\t'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "./lexico.l"
{ *str_scapes++ = ' ';  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "./lexico.l"
{ *str_scapes++ = '\b'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 113 "./lexico.l"
{ *str_scapes++ = '\r'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 114 "./lexico.l"
{ *str_scapes++ = '\f'; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "./lexico.l"
{ *str_scapes++ = '"'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "./lexico.l"
{ 
				/* FIXME No funcionando! */
					int _ii;
					/* Caracteres de escape numéricos para saltos de línea */
					for(_ii = 0; _ii < (*(yytext + 1) - '0'); _ii++) 
						*str_scapes++ = '\n';	
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "./lexico.l"
{
						*str_scapes = 0;
						BEGIN 0; 
						/* REGRESAR EL STRING Y ASIGNARLO AQUÍ */
						strcpy(yylval.cadena, buf);
						return CADENA;
					}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 130 "./lexico.l"
{ printf("Error, Invalid string at line: %d\n", lineno + 1); exit(EXIT_FAILURE);	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 131 "./lexico.l"
{ *str_scapes++ = *yytext; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 133 "./lexico.l"
{comment();}	/* Comentarios */
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 134 "./lexico.l"
{;}		/* Comentarios tipo shell, perl, python, etc */
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 135 "./lexico.l"
{;}		/* Comentarios estilo C++ */
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 136 "./lexico.l"
{;}		/* Comentarios estilo basic */
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 137 "./lexico.l"
{;}		/* Comentarios estilo batch */
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 138 "./lexico.l"
{;}		/* Comentarios estilo SQL */
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 140 "./lexico.l"
{
									return *yytext;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 144 "./lexico.l"
return ARRAY;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 145 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 146 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 147 "./lexico.l"
return LETSET;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 148 "./lexico.l"
return IFTHEN;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 149 "./lexico.l"
return IFEND;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 151 "./lexico.l"
return _LT_;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 152 "./lexico.l"
return _GT_;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 153 "./lexico.l"
return GE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 154 "./lexico.l"
return GE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 155 "./lexico.l"
return SWAP;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 156 "./lexico.l"
return LE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "./lexico.l"
return LE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 158 "./lexico.l"
return EQ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 159 "./lexico.l"
return EQ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 160 "./lexico.l"
return NE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 161 "./lexico.l"
return NE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 162 "./lexico.l"
return AND;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 163 "./lexico.l"
return OR;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 164 "./lexico.l"
return SHIFTLEFT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 165 "./lexico.l"
return SHIFTRIGHT; 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 167 "./lexico.l"
return EXPR_MAS;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 168 "./lexico.l"
return EXPR_MENOS;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 169 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 170 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 171 "./lexico.l"
return EXPR_MUL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 172 "./lexico.l"
return EXPR_NOT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 173 "./lexico.l"
return EXPR_ELEVADO;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 174 "./lexico.l"
return EXPR_MENOR;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 175 "./lexico.l"
return EXPR_MAYOR;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 176 "./lexico.l"
return EXPR_MENORQUE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 177 "./lexico.l"
return EXPR_MAYORQUE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 179 "./lexico.l"
return XOROP;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 181 "./lexico.l"
return ASIGN_ADD;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 182 "./lexico.l"
return ASIGN_SUB;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 183 "./lexico.l"
return ASIGN_MUL;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 184 "./lexico.l"
return ASIGN_DIV;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 185 "./lexico.l"
return ASIGN_POW;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "./lexico.l"
return ASIGN_MOD;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "./lexico.l"
return ASIGN_SHIFTLEFT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 188 "./lexico.l"
return ASIGN_SHIFTRIGHT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 189 "./lexico.l"
return ASIGN_AND;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 190 "./lexico.l"
return ASIGN_OR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 191 "./lexico.l"
return CONCATENATE_DIGITS;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 192 "./lexico.l"
return FACE_HAPPY;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 193 "./lexico.l"
return FACE_SAD;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 194 "./lexico.l"
return FACE_NO;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 196 "./lexico.l"
return PROC;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 197 "./lexico.l"
return EXIT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 198 "./lexico.l"
return FOR;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 199 "./lexico.l"
return CALL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 200 "./lexico.l"
return UNLESS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 201 "./lexico.l"
return AND;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 202 "./lexico.l"
return OR;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 203 "./lexico.l"
return FOREACH;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 204 "./lexico.l"
return INCREMENTAR;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 205 "./lexico.l"
return DECREMENTAR;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 206 "./lexico.l"
return DECLARE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 207 "./lexico.l"
return FUNCTION;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 208 "./lexico.l"
return INT_TYPE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 209 "./lexico.l"
return DECIMAL_TYPE;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 210 "./lexico.l"
return BOOL_TYPE;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 211 "./lexico.l"
return VOID;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 212 "./lexico.l"
return ANDBITS;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 213 "./lexico.l"
return ORBITS;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 214 "./lexico.l"
return OPVAR;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 215 "./lexico.l"
return WHILE;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 216 "./lexico.l"
return DO;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 217 "./lexico.l"
return IF;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 218 "./lexico.l"
return ELSE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 219 "./lexico.l"
return READ;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 220 "./lexico.l"
return PUSH;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 221 "./lexico.l"
return POP;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 222 "./lexico.l"
return PRINT;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 223 "./lexico.l"
return PAR;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 224 "./lexico.l"
return PRINTN;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 225 "./lexico.l"
return ABS;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 226 "./lexico.l"
return PRASCII;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 227 "./lexico.l"
return CLEAR_STACK;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 228 "./lexico.l"
return PUSH_VARS;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 229 "./lexico.l"
return POP_VARS;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 230 "./lexico.l"
return FACTORIAL;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 231 "./lexico.l"
return SUMATORIA;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 232 "./lexico.l"
return RAND;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 233 "./lexico.l"
return BREAK;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 234 "./lexico.l"
return PUTS;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 235 "./lexico.l"
return STRLEN;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 236 "./lexico.l"
return ADDASM;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 237 "./lexico.l"
return SUBASM;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 238 "./lexico.l"
return MOVE;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 239 "./lexico.l"
return MOVE;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 240 "./lexico.l"
return TO;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 241 "./lexico.l"
return MOVASM;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 243 "./lexico.l"
return SQRT;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 244 "./lexico.l"
return ACOS;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 245 "./lexico.l"
return ASIN;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 246 "./lexico.l"
return ATAN;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 247 "./lexico.l"
return CEIL;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 248 "./lexico.l"
return COS;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 249 "./lexico.l"
return COSH;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 250 "./lexico.l"
return EXP;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 251 "./lexico.l"
return FLOOR;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 252 "./lexico.l"
return LN;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 253 "./lexico.l"
return SIN;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 254 "./lexico.l"
return SINH;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 255 "./lexico.l"
return TAN;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 256 "./lexico.l"
return TANH;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 257 "./lexico.l"
return SYSTEM;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 259 "./lexico.l"
return DECLARE_G;	/* declare_g(...); */
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 261 "./lexico.l"
;
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 262 "./lexico.l"
{ lineno++; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 263 "./lexico.l"
{
				char __linea[40];
				sprintf(__linea, "Carácter desconocido en la línea %d\n", lineno + 1);
				fputs(__linea, stdout);

				/* FIXME Decidir si se va a continuar o al error parar todo */
				
				/*yyerror(__linea);*/
	}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 273 "./lexico.l"
ECHO;
	YY_BREAK
#line 1844 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 377 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 377 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 376);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 273 "./lexico.l"



comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0);
/*		putchar(c);*/

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	/*if (c != 0)
		putchar(c1);*/
}

int yywrap(void) {
	return 1;
}

