
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 140
#define YY_END_OF_BUFFER 141
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[379] =
    {   0,
        0,    0,    0,    0,  141,  139,  137,  138,   27,    9,
      139,   27,   27,   27,   93,   27,   27,   27,   27,   27,
       27,    3,    3,   27,   27,   27,   27,   27,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   27,  139,
        2,    2,  139,   20,   19,   18,   20,   43,    0,   22,
        0,   66,    0,   45,   69,    0,   63,   61,    0,   62,
        0,    0,    0,    0,   71,   21,    0,   64,    0,    3,
        0,    0,   73,   72,    0,   29,   74,   30,   47,   39,
       41,   36,   48,    8,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   96,    0,
        0,    0,    0,    0,    0,    0,    0,   97,    0,    0,
      131,    0,    0,    0,   54,   82,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  120,    0,    0,    0,    0,   65,    0,    0,
        0,   70,   46,   17,   13,   15,   10,   16,   14,   12,
       11,    6,    0,   92,    0,   26,   42,   37,   35,   40,
       34,   44,    0,   23,    3,    5,    7,    0,   25,   38,
       67,   68,  105,    0,  116,   81,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  127,    0,    0,    0,

        0,    0,   33,    0,    0,  129,    0,    0,   78,    0,
        0,   88,   31,   49,    0,    0,  121,   54,  103,  101,
       53,    0,    0,    0,    0,    0,    0,    0,  102,  132,
        0,    0,    0,  117,    0,    0,  134,    0,    0,    0,
        0,   60,   94,    0,    0,    0,  123,    0,  124,    0,
      125,   90,    0,   79,  126,    0,    0,  128,    0,    0,
       85,    0,   98,    0,    0,   77,    0,    0,    0,    0,
       84,    0,    0,  118,    0,    0,    0,   76,  100,  114,
      112,   99,  133,    0,  122,    0,    0,    0,  135,   32,
        0,   91,    0,    0,    0,   24,    0,   28,    0,  113,

        0,    0,    0,    0,    0,   51,    0,  130,    0,    0,
       57,   56,   50,    0,    0,  102,    0,   52,    0,    0,
        0,    0,   95,    0,    0,  119,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  104,    0,
      115,    0,  136,   80,    0,    1,    0,    4,   89,   86,
       55,    0,   83,    0,    0,    0,  109,  106,    0,    0,
        0,    0,    0,   87,   59,   58,  108,    0,    0,    0,
      110,  111,    0,  107,    0,    0,   75,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   16,   23,
       24,   25,   16,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,   53,   54,   55,   56,    1,   57,   58,   29,   30,

       59,   60,   61,   34,   62,   36,   37,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   47,   48,   49,   50,
       51,   36,   16,   72,   16,   16,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    2,    3,    4,    1,    4,    4,    1,    1,    1,
        4,    4,    4,    1,    4,    1,    4,    4,    4,    5,
        5,    2,    1,    4,    1,    4,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    4,    1,    4,    2,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    4
    } ;

static yyconst flex_int16_t yy_base[390] =
    {   0,
        0,    0,   70,   71,  676,  677,  677,  677,  651,  677,
      671,    0,   51,   68,  663,  677,  648,  647,   66,  646,
       65,   76,   67,   69,   78,  645,   74,    0,  114,   64,
      107,   69,  111,  130,  677,   72,  138,  159,   45,   70,
      154,  175,  208,  180,   75,   80,  634,   81,  643,  640,
      197,  188,   83,  677,  677,  677,  232,  677,  662,  677,
      656,  677,  596,  677,  677,  651,  677,  677,  658,  677,
      592,   47,   94,  600,  677,  677,  655,  677,   99,  171,
        0,  158,  186,  200,  654,  677,  204,  631,  631,  677,
      677,  677,  630,    0,  118,  163,  623,  622,  161,  213,

      185,  195,  168,  206,   74,  209,  217,  622,  220,  219,
      229,  242,  242,  621,  232,  236,  241,  677,  262,  240,
      677,  248,  254,  601,  249,  677,  263,  268,  287,  270,
      277,  294,  597,  277,  285,  296,  283,  286,  306,  286,
      296,  298,  677,  300,  132,  304,  299,  677,  591,  585,
      319,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  637,  573,  677,  640,  677,  677,  677,  677,  677,
      677,  677,  639,  677,  338,    0,  677,  638,  677,  677,
      677,  677,  677,  302,  677,  677,  333,  322,  330,  329,
      333,  340,  335,  336,  348,  332,  606,  344,  349,  591,

      350,  332,  677,  341,  340,  677,  343,  350,  353,  609,
      349,  677,  677,  677,  354,  359,  370,  677,  677,  589,
      677,  370,  377,  607,  601,  374,  604,  568,  677,  563,
      377,  376,  385,  677,  377,  378,  557,  386,  396,  555,
      390,  677,  677,  505,  563,  499,  677,  507,  677,  397,
      677,  677,  518,  677,  677,  387,  386,  677,  396,  406,
      677,  409,  677,  503,  406,  677,  398,  399,  414,  399,
      677,  406,  417,  677,  425,  521,  408,  677,  501,  677,
      677,  677,  677,  436,  677,  438,  413,  441,  677,  677,
      428,  677,  443,  482,  543,  677,  477,  677,  436,  677,

      433,  524,  450,  436,  511,  677,  437,  677,  409,  448,
      445,  446,  677,  446,  450,  451,  465,  677,  453,  453,
      457,  454,  677,  284,  168,  677,  458,    0,  470,  478,
      470,  482,  197,  479,  170,  166,  478,  490,  677,  482,
      677,  484,  677,  677,  140,  677,  500,    0,  677,  677,
      677,  503,  677,  491,  503,  504,  677,  677,  494,  497,
       96,  127,  502,  677,  677,  677,  677,  511,   91,   79,
      677,  677,   44,  677,   46,   16,  677,  677,  568,  575,
      582,  588,  594,  601,  608,  611,  617,  624,  626
    } ;

static yyconst flex_int16_t yy_def[390] =
    {   0,
      378,    1,  379,  379,  378,  378,  378,  378,  378,  378,
      380,  381,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  382,  378,  378,  378,  383,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  380,  378,
      381,  378,  378,  378,  378,  378,  378,  378,  384,  378,
      378,  378,  378,  378,  378,  378,  385,  378,  378,  378,
      386,  382,  382,  382,  387,  378,  382,  378,  378,  378,
      378,  378,  378,  383,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  381,  378,  378,  384,  378,  378,  378,  378,  378,
      378,  378,  385,  378,  378,  386,  378,  387,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  388,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  388,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  389,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  389,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,    0,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378
    } ;

static yyconst flex_int16_t yy_nxt[750] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   16,   17,   18,   16,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   35,   36,   35,   35,   37,   38,   39,
       40,   41,   35,   42,   43,   44,   45,   46,   47,   48,
       35,   16,    6,   16,   49,   50,   29,   51,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   35,   52,   43,
       44,   53,   55,   55,   62,   56,   56,   64,   76,  377,
       83,   84,   69,   77,   79,  125,   80,   80,   78,   70,
       85,   65,   86,   79,   88,   80,   80,   92,   93,  108,

       89,   90,  376,  118,  102,  168,  152,  103,  194,  109,
      125,  119,  375,  126,  144,  374,   63,  169,  175,  175,
      145,  147,   57,   57,   71,   81,   72,  108,   73,  102,
       74,  118,  103,  104,  109,  194,  119,  105,  126,  144,
       87,   95,   96,   97,  106,  145,  147,  107,  110,  111,
      112,  373,  170,   98,  153,  370,  114,   99,  100,  101,
      113,  369,  183,  104,  171,  105,  240,  115,  120,  106,
      116,   95,  107,  110,  111,  112,  117,  121,   98,  177,
      127,  378,   99,  100,  101,  122,  114,  183,   79,  123,
       80,   80,  115,  240,  128,  116,  120,  129,  192,  124,

      130,  131,  121,  184,  187,  132,  141,  177,  361,  378,
      127,  190,  356,  142,  131,  122,  355,  123,  132,  128,
      143,  177,  129,  378,  124,  177,  192,  378,  184,  187,
      353,  131,  346,  132,  133,  191,  141,  102,  134,  195,
      103,  190,  135,  193,  131,  143,  151,  188,  136,  200,
      137,  154,  154,  138,  139,  150,  196,  189,  140,  199,
      191,  197,  102,  201,  133,  103,  134,  195,  193,  135,
      202,  203,  208,  136,  188,  137,  205,  200,  138,  209,
      210,  196,  189,  206,  199,  213,  197,  204,  201,  155,
      211,  156,  214,  216,  218,  202,  157,  208,  215,  158,

      159,  160,  161,  205,  209,  210,  219,  212,  206,  220,
      213,  221,  204,  222,  225,  226,  227,  214,  216,  218,
      228,  223,  213,  231,  230,  345,  232,  224,  238,  233,
      236,  219,  212,  234,  220,  237,  221,  239,  241,  225,
      226,  227,  242,  222,  235,  228,  247,  213,  223,  230,
      228,  232,  224,  231,  233,  236,  238,  175,  175,  248,
      237,  249,  239,  234,  250,  241,  253,  242,  251,  235,
      252,  247,  254,  255,  256,  228,  257,  264,  259,  203,
      263,  260,  245,  269,  265,  266,  249,  261,  267,  248,
      268,  250,  271,  251,  272,  252,  253,  254,  255,  273,

      274,  257,  264,  287,  256,  259,  260,  203,  263,  265,
      266,  269,  261,  267,  276,  268,  277,  271,  280,  272,
      284,  285,  286,  288,  273,  290,  291,  293,  274,  299,
      301,  302,  304,  287,  303,  305,  306,  333,  307,  276,
      309,  277,  308,  280,  310,  284,  285,  286,  288,  311,
      290,  314,  293,  316,  291,  301,  302,  299,  320,  303,
      312,  313,  304,  307,  306,  305,  318,  308,  319,  310,
      309,  321,  322,  323,  311,  326,  329,  327,  316,  330,
      332,  314,  334,  320,  338,  312,  313,  335,  336,  337,
      339,  340,  341,  342,  318,  343,  319,  322,  344,  321,

      326,  323,  327,  347,  330,  332,  329,  349,  350,  334,
      351,  338,  335,  336,  337,  339,  352,  341,  342,  354,
      343,  340,  357,  344,  358,  359,  362,  360,  347,  363,
      364,  368,  349,  365,  366,  351,  350,  372,  367,  371,
      331,  328,  325,  352,  354,  296,  324,  357,  317,  315,
      359,  358,  360,  292,  300,  364,  362,  298,  368,  363,
      297,  365,  366,  367,  371,  296,  294,  372,   54,   54,
       54,   54,   54,   54,   54,   59,   59,   59,   59,   59,
       59,   59,   61,   61,  292,   61,   61,   61,   61,   82,
      289,   82,   82,   82,   82,   94,  283,  282,   94,   94,

       94,  165,  165,  165,  165,  165,  165,  165,  173,  173,
      173,  173,  173,  173,  173,  176,  176,  178,  178,  178,
      178,  178,  178,  178,  295,  295,  295,  295,  295,  295,
      295,  348,  348,  281,  279,  278,  275,  270,  262,  258,
      179,  174,  166,  246,  162,  244,  243,  229,  217,  207,
      198,  186,  185,  182,  181,  180,  179,  174,  172,  167,
      166,  164,  163,  162,   60,  149,  148,  146,   91,   75,
       68,   67,   66,   60,   58,  378,    5,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378
    } ;

static yyconst flex_int16_t yy_chk[750] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,   13,    3,    4,   14,   21,  376,
       24,   24,   19,   21,   23,   39,   23,   23,   21,   19,
       24,   14,   24,   22,   25,   22,   22,   27,   27,   32,

       25,   25,  375,   36,   30,   72,   53,   30,  105,   32,
       39,   36,  373,   40,   45,  370,   13,   72,   79,   79,
       46,   48,    3,    4,   19,   22,   19,   32,   19,   30,
       19,   36,   30,   31,   32,  105,   36,   31,   40,   45,
       24,   29,   29,   29,   31,   46,   48,   31,   33,   33,
       33,  369,   73,   29,   53,  362,   34,   29,   29,   29,
       33,  361,   95,   31,   73,   31,  145,   34,   37,   31,
       34,   29,   31,   33,   33,   33,   34,   37,   29,   82,
       41,   82,   29,   29,   29,   38,   34,   95,   80,   38,
       80,   80,   34,  145,   41,   34,   37,   41,  103,   38,

       41,   42,   37,   96,   99,   42,   44,   83,  345,   83,
       41,  101,  336,   44,   52,   38,  335,   38,   52,   41,
       44,   84,   41,   84,   38,   87,  103,   87,   96,   99,
      333,   42,  325,   42,   43,  102,   44,   51,   43,  106,
       51,  101,   43,  104,   52,   44,   52,  100,   43,  110,
       43,   57,   57,   43,   43,   51,  107,  100,   43,  109,
      102,  107,   51,  110,   43,   51,   43,  106,  104,   43,
      111,  112,  115,   43,  100,   43,  113,  110,   43,  116,
      117,  107,  100,  113,  109,  120,  107,  112,  110,   57,
      119,   57,  122,  123,  125,  111,   57,  115,  122,   57,

       57,   57,   57,  113,  116,  117,  127,  119,  113,  128,
      120,  128,  112,  129,  130,  130,  131,  122,  123,  125,
      132,  129,  134,  136,  135,  324,  137,  129,  142,  138,
      140,  127,  119,  139,  128,  141,  128,  144,  146,  130,
      130,  131,  147,  129,  139,  151,  184,  134,  129,  135,
      132,  137,  129,  136,  138,  140,  142,  175,  175,  187,
      141,  188,  144,  139,  189,  146,  192,  147,  190,  139,
      191,  184,  193,  194,  195,  151,  196,  202,  198,  199,
      201,  198,  151,  209,  204,  205,  188,  198,  207,  187,
      208,  189,  211,  190,  215,  191,  192,  193,  194,  216,

      217,  196,  202,  235,  195,  198,  198,  199,  201,  204,
      205,  209,  198,  207,  222,  208,  223,  211,  226,  215,
      231,  232,  233,  236,  216,  238,  239,  241,  217,  250,
      256,  257,  260,  235,  259,  262,  265,  309,  267,  222,
      269,  223,  268,  226,  270,  231,  232,  233,  236,  272,
      238,  275,  241,  277,  239,  256,  257,  250,  287,  259,
      273,  273,  260,  267,  265,  262,  284,  268,  286,  270,
      269,  288,  291,  293,  272,  299,  303,  301,  277,  304,
      307,  275,  310,  287,  315,  273,  273,  311,  312,  314,
      316,  317,  319,  320,  284,  321,  286,  291,  322,  288,

      299,  293,  301,  327,  304,  307,  303,  329,  330,  310,
      331,  315,  311,  312,  314,  316,  332,  319,  320,  334,
      321,  317,  337,  322,  338,  340,  347,  342,  327,  352,
      354,  360,  329,  355,  356,  331,  330,  368,  359,  363,
      305,  302,  297,  332,  334,  295,  294,  337,  279,  276,
      340,  338,  342,  264,  253,  354,  347,  248,  360,  352,
      246,  355,  356,  359,  363,  245,  244,  368,  379,  379,
      379,  379,  379,  379,  379,  380,  380,  380,  380,  380,
      380,  380,  381,  381,  240,  381,  381,  381,  381,  382,
      237,  382,  382,  382,  382,  383,  230,  228,  383,  383,

      383,  384,  384,  384,  384,  384,  384,  384,  385,  385,
      385,  385,  385,  385,  385,  386,  386,  387,  387,  387,
      387,  387,  387,  387,  388,  388,  388,  388,  388,  388,
      388,  389,  389,  227,  225,  224,  220,  210,  200,  197,
      178,  173,  165,  163,  162,  150,  149,  133,  124,  114,
      108,   98,   97,   93,   89,   88,   85,   77,   74,   71,
       69,   66,   63,   61,   59,   50,   49,   47,   26,   20,
       18,   17,   15,   11,    9,    5,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./lexico.l"
/* Leo Gutiérrez Ramírez, leorocko13@hotmail.com */
#line 3 "./lexico.l"
	#include <stdlib.h>
	#include "estructuras.h"
	#include "constantes.h"
	#include "y.tab.h"
	extern char opVar[4];
	extern unsigned int lineno;
	char buf[100];
	char *s;			/* Puntero para ir acumulando caracteres de escape */

#line 760 "lex.yy.c"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 14 "./lexico.l"


#line 951 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 379 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 677 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "./lexico.l"
yylineno;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "./lexico.l"
{
						/* TODO Revisar esto con calma */
						if(isupper(*yytext))
							yylval.sIndex = tolower(*yytext) - 'a';
						else
							yylval.sIndex = *yytext - 'a';
						return VARIABLE;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "./lexico.l"
{
						yylval.iValue = atof(yytext);
						return INTEGER;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "./lexico.l"
{	
									char *__elemento = strtok(yytext, ".");
									__elemento = strtok(NULL, ".");
									/*printf("Detectado: '%s'\n", __elemento);*/

									unsigned i;
									for(i = 0; i < N_CONST; i++) {
										if(strcmp(__elemento, consts[i].const_str) == 0) {
											yylval.iValue = consts[i].value;
											return INTEGER;
										}
									}
									fprintf(stderr, "Error, constante no identificada 'const.%s'\n", __elemento);
									exit(EXIT_FAILURE);
									
								}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "./lexico.l"
{
						/*char *__p;	*/
						/* SHIT */
						/*long long n = strtoll(yytext, &__p, 16);
						if(*__p == 0)*/
							yylval.iValue = atof(yytext);
						/*else
							yylval.iValue = 0;*/
						return INTEGER;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "./lexico.l"
{
						strcpy(yylval.nameFunction, yytext);
						yylval.nameFunction[strlen(yylval.nameFunction)] = '\0';
						return FUNCNAME;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "./lexico.l"
{
							unsigned _i_;
							strcpy(yylval.identificador, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.identificador); _i_++)
								if(isalpha(yylval.identificador[_i_]) && isupper(yylval.identificador[_i_]))
									yylval.identificador[_i_] = tolower(yylval.identificador[_i_]);
							return ID;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "./lexico.l"
{
							
							unsigned _i_;
							strcpy(yylval.idArray, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.idArray); _i_++)
								if(isalpha(yylval.idArray[_i_]) && isupper(yylval.idArray[_i_]))
									yylval.idArray[_i_] = tolower(yylval.idArray[_i_]);
							return ID_ARRAY;

}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "./lexico.l"
{ BEGIN	STRING; s = buf; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 86 "./lexico.l"
{ *s++ = '\n'; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 "./lexico.l"
{ *s++ = '\t'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 88 "./lexico.l"
{ *s++ = ' ';  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "./lexico.l"
{ *s++ = '\b'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 "./lexico.l"
{ *s++ = '\r'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "./lexico.l"
{ *s++ = '\f'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "./lexico.l"
{ *s++ = '"'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 "./lexico.l"
{ 
				/* FIXME No funcionando! */
					int _ii;
					/* Caracteres de escape numéricos para saltos de línea */
					for(_ii = 0; _ii < (*(yytext + 1) - '0'); _ii++) 
						*s++ = '\n';	
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 100 "./lexico.l"
{
						*s = 0;
						BEGIN 0; 
						/* REGRESAR EL STRING Y ASIGNARLO AQUÍ */
						strcpy(yylval.cadena, buf);
						return CADENA;
					}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 107 "./lexico.l"
{ printf("Error, Invalid string"); exit(EXIT_FAILURE);	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 108 "./lexico.l"
{ *s++ = *yytext; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "./lexico.l"
{comment();}	/* Comentarios */
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 111 "./lexico.l"
{;}		/* Comentarios tipo shell, perl, python, etc */
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 112 "./lexico.l"
{;}		/* Comentarios estilo C++ */
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 113 "./lexico.l"
{;}		/* Comentarios estilo basic */
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 114 "./lexico.l"
{;}		/* Comentarios estilo batch */
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 115 "./lexico.l"
{;}		/* Comentarios estilo SQL */
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 117 "./lexico.l"
{
									return *yytext;
					}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 121 "./lexico.l"
return ARRAY;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 122 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 123 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 124 "./lexico.l"
return LETSET;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 125 "./lexico.l"
return IFTHEN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 126 "./lexico.l"
return IFEND;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 127 "./lexico.l"
return _LT_;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "./lexico.l"
return _GT_;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 129 "./lexico.l"
return GE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 130 "./lexico.l"
return GE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 131 "./lexico.l"
return SWAP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 132 "./lexico.l"
return LE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "./lexico.l"
return LE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "./lexico.l"
return EQ;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 135 "./lexico.l"
return EQ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 136 "./lexico.l"
return NE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 137 "./lexico.l"
return NE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 138 "./lexico.l"
return AND;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 139 "./lexico.l"
return OR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 140 "./lexico.l"
return SHIFTLEFT;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 141 "./lexico.l"
return SHIFTRIGHT; 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 142 "./lexico.l"
return EXPR_MAS;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 143 "./lexico.l"
return EXPR_MENOS;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 144 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 145 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 146 "./lexico.l"
return EXPR_MUL;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 147 "./lexico.l"
return EXPR_NOT;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 148 "./lexico.l"
return EXPR_ELEVADO;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 149 "./lexico.l"
return EXPR_MENOR;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 150 "./lexico.l"
return EXPR_MAYOR;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 151 "./lexico.l"
return EXPR_MENORQUE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 152 "./lexico.l"
return EXPR_MAYORQUE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 153 "./lexico.l"
return XOROP;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 154 "./lexico.l"
return ASIGN_ADD;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 155 "./lexico.l"
return ASIGN_SUB;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 156 "./lexico.l"
return ASIGN_MUL;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 157 "./lexico.l"
return ASIGN_DIV;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 158 "./lexico.l"
return ASIGN_POW;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 159 "./lexico.l"
return ASIGN_MOD;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 160 "./lexico.l"
return ASIGN_SHIFTLEFT;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 161 "./lexico.l"
return ASIGN_SHIFTRIGHT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 162 "./lexico.l"
return ASIGN_AND;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 163 "./lexico.l"
return ASIGN_OR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 164 "./lexico.l"
return CONCATENATE_DIGITS;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 165 "./lexico.l"
return FACE_HAPPY;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 166 "./lexico.l"
return FACE_SAD;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 167 "./lexico.l"
return FACE_NO;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 168 "./lexico.l"
return PRINCIPIO;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 169 "./lexico.l"
return PROC;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 170 "./lexico.l"
return EXIT;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 171 "./lexico.l"
return FOR;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "./lexico.l"
return CALL;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 173 "./lexico.l"
return UNLESS;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 174 "./lexico.l"
return AND;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 175 "./lexico.l"
return OR;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 176 "./lexico.l"
return FOREACH;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 177 "./lexico.l"
return INCREMENTAR;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 178 "./lexico.l"
return DECREMENTAR;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 179 "./lexico.l"
return DECLARE;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 180 "./lexico.l"
return FUNCTION;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 181 "./lexico.l"
return INT_TYPE;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 182 "./lexico.l"
return DECIMAL_TYPE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 183 "./lexico.l"
return BOOL_TYPE;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 184 "./lexico.l"
return VOID;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 185 "./lexico.l"
return ANDBITS;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 186 "./lexico.l"
return ORBITS;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 187 "./lexico.l"
return OPVAR;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 188 "./lexico.l"
return WHILE;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 189 "./lexico.l"
return DO;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 190 "./lexico.l"
return IF;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 191 "./lexico.l"
return ELSE;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 192 "./lexico.l"
return READ;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 193 "./lexico.l"
return PUSH;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 194 "./lexico.l"
return POP;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 195 "./lexico.l"
return PRINT;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 196 "./lexico.l"
return PAR;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 197 "./lexico.l"
return PRINTN;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 198 "./lexico.l"
return ABS;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 199 "./lexico.l"
return PRASCII;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 200 "./lexico.l"
return CLEAR_STACK;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 201 "./lexico.l"
return PUSH_VARS;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 202 "./lexico.l"
return POP_VARS;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 203 "./lexico.l"
return FACTORIAL;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 204 "./lexico.l"
return SUMATORIA;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 205 "./lexico.l"
return RAND;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 206 "./lexico.l"
return BREAK;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 207 "./lexico.l"
return PUTS;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 208 "./lexico.l"
return STRLEN;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 209 "./lexico.l"
return ADDASM;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 210 "./lexico.l"
return SUBASM;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 211 "./lexico.l"
return MOVE;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 212 "./lexico.l"
return MOVE;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 213 "./lexico.l"
return TO;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 214 "./lexico.l"
return MOVASM;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 215 "./lexico.l"
return SQRT;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 216 "./lexico.l"
return ACOS;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 217 "./lexico.l"
return ASIN;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 218 "./lexico.l"
return ATAN;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 219 "./lexico.l"
return CEIL;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 220 "./lexico.l"
return COS;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 221 "./lexico.l"
return COSH;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 222 "./lexico.l"
return EXP;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 223 "./lexico.l"
return FLOOR;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 224 "./lexico.l"
return LN;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 225 "./lexico.l"
return SIN;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 226 "./lexico.l"
return SINH;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 227 "./lexico.l"
return TAN;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 228 "./lexico.l"
return TANH;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 229 "./lexico.l"
return SYSTEM;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 230 "./lexico.l"
;
	YY_BREAK
case 138:
/* rule 138 can match eol */
YY_RULE_SETUP
#line 231 "./lexico.l"
{ lineno++; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 232 "./lexico.l"
{
				char __linea[40];
				sprintf(__linea, "Carácter desconocido en la línea %d\n", lineno + 1);
				fputs(__linea, stdout);

				/* FIXME Decidir si se va a continuar o al error parar todo */
				
				/*yyerror(__linea);*/
	}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 242 "./lexico.l"
ECHO;
	YY_BREAK
#line 1817 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 379 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 379 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 378);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 242 "./lexico.l"



comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0);
/*		putchar(c);*/

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	/*if (c != 0)
		putchar(c1);*/
}

int yywrap(void) {
	return 1;
}

